apiVersion: v1
kind: Namespace
metadata:
    name: hw2-app
    labels:
        name: hw2-app
---
apiVersion: v1
kind: Service
metadata:
    name: postgres
    namespace: hw2-app
    labels:
        app: postgres
spec:
    type: NodePort
    ports:
        -   port: 5432
    selector:
        app: postgres
---
apiVersion: v1
kind: Service
metadata:
    name: hw2-service
    namespace: hw2-app
spec:
    selector:
        app: hw2
    ports:
        -   protocol: TCP
            port: 8000
            targetPort: web
    type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: postgres-statefulset
    namespace: hw2-app
spec:
    serviceName: "postgres"
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                -   name: postgres
                    image: postgres:latest
                    ports:
                        -   containerPort: 5432
                            name: postgredb
                    env:
                        -   name: POSTGRES_DB
                            value: myapp
                        -   name: POSTGRES_USER
                            value: myuser
                        -   name: POSTGRES_PASSWORD
                            value: passwd
                    volumeMounts:
                        -   name: postgredb
                            mountPath: /var/lib/postgresql/data
                            subPath: postgres
    volumeClaimTemplates:
        -   metadata:
                name: postgredb
            spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: standard
                resources:
                    requests:
                        storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hw2-deployment
    namespace: hw2-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: hw2
    template:
        metadata:
            labels:
                app: hw2
        spec:
            containers:
                -   name: otus-hw2
                    image: washburn62/otus_trukhin_hw2:v1
                    env:
                        -   name: DATABASE_URL
                            value: postgresql+psycopg2://myuser:passwd@postgres/myapp
                    ports:
                        -   name: web
                            containerPort: 8000
